name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-macos:
    name: macOS x86_64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: brew install sdl2 coreutils
    - name: Build
      run: make -j$(sysctl -n hw.logicalcpu)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zelda3-macos-x86_64
        path: |
          zelda3
          zelda3.ini
        if-no-files-found: error

  build-linux:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev
    - name: Install Python deps
      run: pip install pillow pyyaml
    - name: Build
      run: make -j$(nproc)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zelda3-linux-x86_64
        path: |
          zelda3
          zelda3.ini
        if-no-files-found: error
